#!/usr/bin/env python3
"""GUI editor for the VGM multi-MCU player's SD-card config file (vgmplay.ini).

Per sound chip: enable/disable, chip-select GPIO, an optional per-byte
CS-pulse gap (microseconds), and an optional output volume (percent of
unity, 0-255). Plus general (non-chip) settings: shuffle playback order,
the skip button's GPIO, preview mode (cut every song short after N
seconds), recursive mode (walk every subfolder instead of just the SD card
root), and the SD-card-relative folder to start scanning from. Mirrors the firmware parser in master/src/player_config.c -- section names
ignore case / '-' / '_' / space, the same key aliases are accepted, and the
same reserved-pin / duplicate-CS checks are surfaced as warnings.

Standard library only (tkinter). Run with no arguments for the GUI, or
`--check FILE` to parse a file and print the result on the console.
"""

import argparse
import glob
import os
import re
import sys

# (canonical section, display name, default CS GPIO, default gap us or None)
# Order = the order sections are written back out (matches firmware/vgmplay.ini).
CHIPS = [
    ("sn76489", "SN76489",   12, None),
    ("ym2612",  "YM2612",    13, None),
    ("ay8910",  "AY-3-8910", 14, 120),
    ("ym2413",  "YM2413",    15, None),
    ("ym2151",  "YM2151",    20, 0),
    ("ym2203",  "YM2203",    21, None),
    ("scc",     "SCC",       22, None),
    ("segapcm", "SegaPCM",   26, None),
]
CHIP_ORDER = [c[0] for c in CHIPS]
DISPLAY = {c[0]: c[1] for c in CHIPS}
DEFAULT_CS = {c[0]: c[2] for c in CHIPS}
DEFAULT_GAP = {c[0]: c[3] for c in CHIPS}

# Sentinel `cur` value for the one non-chip section, [player] (general
# playback settings: shuffle, skip_button, preview/preview_seconds,
# recursive, root_dir). Mirrors master/src/player_config.c's SECTION_PLAYER.
PLAYER_SECTION = "player"

# normalized section name -> canonical
SECTION_ALIASES = {
    "sn76489": "sn76489",
    "ym2413": "ym2413",
    "ym2612": "ym2612",
    "ay8910": "ay8910", "ay38910": "ay8910",
    "ym2151": "ym2151",
    "ym2203": "ym2203",
    "scc": "scc", "k051649": "scc",
    "segapcm": "segapcm",
}

# normalized key (lower, '-'/'_'/space removed) -> field
KEY_ALIASES = {
    "enabled": "enabled", "enable": "enabled", "present": "enabled", "on": "enabled",
    "cs": "cs", "csgpio": "cs", "cspin": "cs", "pin": "cs",
    "gap": "gap", "gapus": "gap",
    "volume": "volume", "vol": "volume",
}

BOOL_TRUE = {"1", "on", "yes", "true", "enabled", "enable"}
BOOL_FALSE = {"0", "off", "no", "false", "disabled", "disable"}

# GPIO -> what the master already uses it for (a CS here fights that peripheral).
# The skip button is NOT in this static table -- its GPIO is configurable
# ([player] skip_button, default 2), so validate() adds it dynamically from
# whatever the current rows say (mirrors slave_bus.c's
# slave_bus_set_skip_button_gpio(), which does the same on the firmware side).
RESERVED_PINS = {
    0: "OLED I2C0 SDA", 1: "OLED I2C0 SCL",
    10: "slave bus SPI1 SCK", 11: "slave bus SPI1 MOSI",
    16: "SD card SPI0 MISO", 17: "SD card SPI0 CS",
    18: "SD card SPI0 SCK", 19: "SD card SPI0 MOSI",
}
CS_MIN, CS_MAX = 0, 28
DEFAULT_SKIP_BUTTON_GPIO = 2       # master/src/main.c's PIN_BTN_SKIP
DEFAULT_PREVIEW_SECONDS = 30       # master/src/player_config.c's s_preview_seconds
ROOT_DIR_BUF_SZ = 128              # master/src/player_config.c's ROOT_DIR_BUF_SZ (incl. NUL)


def normalize_root_dir(v):
    """Strip an optional FatFs-style "0:" drive prefix and leading/trailing
    slashes, exactly like player_config.c's root_dir parsing, so "0:/GAMES/
    Sega/", "/GAMES/Sega" and "GAMES/Sega" all end up the same."""
    if v[:2].lower() == "0:":
        v = v[2:]
    return v.strip("/")

INI_HEADER = """\
; vgmplay.ini -- VGM multi-MCU player (master) configuration
; Generated by tools/config_gui/vgmplay_config_gui.py -- hand edits to
; comments are not preserved when this tool rewrites the file.
;
; Copy to the ROOT of the SD card (next to the .vgm/.vgz files). Optional:
; with no file the firmware's built-in defaults are used. Section names
; ignore case, '-', '_' and spaces. Lines starting with ; or # are comments.
"""


def _norm(s):
    return re.sub(r"[-_ ]", "", s.strip().lower())


def parse_bool(v):
    lv = v.strip().lower()
    if lv in BOOL_TRUE:
        return True
    if lv in BOOL_FALSE:
        return False
    return None


def parse_ini(text):
    """Return (settings, notes).

    settings: {canonical_chip: {"enabled": bool?, "cs": int?, "gap": int?,
    "volume": int?}, PLAYER_SECTION: {"shuffle": bool?, "skip_button": int?,
    "preview": bool?, "preview_seconds": int?, "recursive": bool?,
    "root_dir": str?}}
    notes:    list of human-readable strings about anything odd in the file.
    """
    settings = {}
    notes = []
    cur = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line[0] in ";#":
            continue
        if line.startswith("["):
            end = line.find("]")
            if end < 0:
                notes.append(f"line {lineno}: malformed section header, ignored")
                continue
            name = line[1:end].strip()
            if _norm(name) == "player":
                cur = PLAYER_SECTION
            else:
                cur = SECTION_ALIASES.get(_norm(name))
                if cur is None:
                    notes.append(f"line {lineno}: unknown chip section [{name}], skipped")
            continue
        if "=" not in line:
            notes.append(f"line {lineno}: no '=' , ignored ({line!r})")
            continue
        rawkey, rawval = line.split("=", 1)
        val = re.split(r"[;#]", rawval, 1)[0].strip()
        if cur is None:
            notes.append(f"line {lineno}: '{rawkey.strip()}' outside any [chip] section, skipped")
            continue
        if cur == PLAYER_SECTION:
            nk = _norm(rawkey)
            if nk == "shuffle":
                b = parse_bool(val)
                if b is None:
                    notes.append(f"line {lineno}: bad boolean '{val}' for shuffle")
                else:
                    settings.setdefault(PLAYER_SECTION, {})["shuffle"] = b
            elif nk in ("skipbutton", "skipgpio", "skippin"):
                if not re.fullmatch(r"\d+", val):
                    notes.append(f"line {lineno}: bad number '{val}' for skip_button")
                elif not (CS_MIN <= int(val) <= CS_MAX):
                    notes.append(f"line {lineno}: skip_button GPIO{val} out of range ({CS_MIN}-{CS_MAX})")
                else:
                    settings.setdefault(PLAYER_SECTION, {})["skip_button"] = int(val)
            elif nk == "preview":
                b = parse_bool(val)
                if b is None:
                    notes.append(f"line {lineno}: bad boolean '{val}' for preview")
                else:
                    settings.setdefault(PLAYER_SECTION, {})["preview"] = b
            elif nk == "previewseconds":
                if not re.fullmatch(r"\d+", val) or int(val) == 0:
                    notes.append(f"line {lineno}: bad number '{val}' for preview_seconds (>0)")
                else:
                    settings.setdefault(PLAYER_SECTION, {})["preview_seconds"] = int(val)
            elif nk == "recursive":
                b = parse_bool(val)
                if b is None:
                    notes.append(f"line {lineno}: bad boolean '{val}' for recursive")
                else:
                    settings.setdefault(PLAYER_SECTION, {})["recursive"] = b
            elif nk in ("rootdir", "folder", "dir"):
                settings.setdefault(PLAYER_SECTION, {})["root_dir"] = normalize_root_dir(val)
            else:
                notes.append(f"line {lineno}: unknown key '{rawkey.strip()}' in [player], ignored")
            continue
        key = KEY_ALIASES.get(_norm(rawkey))
        if key is None:
            notes.append(f"line {lineno}: unknown key '{rawkey.strip()}', ignored")
            continue
        d = settings.setdefault(cur, {})
        if key == "enabled":
            b = parse_bool(val)
            if b is None:
                notes.append(f"line {lineno}: bad boolean '{val}' for {DISPLAY[cur]}")
            else:
                d["enabled"] = b
        else:  # cs / gap / volume
            if not re.fullmatch(r"\d+", val):
                notes.append(f"line {lineno}: bad number '{val}' for {key} ({DISPLAY[cur]})")
            else:
                d[key] = int(val)
    return settings, notes


def rows_from_settings(settings):
    """Merge parsed settings over the built-in defaults into a full row dict.

    Includes CHIP_ORDER's per-chip rows plus one PLAYER_SECTION entry
    ({"shuffle": bool, "skip_button": int?, "preview": bool,
    "preview_seconds": int?, "recursive": bool, "root_dir": str}) for the
    non-chip [player] section.
    """
    rows = {}
    for chip in CHIP_ORDER:
        s = settings.get(chip, {})
        rows[chip] = {
            "enabled": s.get("enabled", True),
            "cs": s.get("cs", DEFAULT_CS[chip]),
            "gap": s.get("gap", None),  # None -> use firmware default, no line written
            "volume": s.get("volume", None),  # None -> use firmware default (100), no line written
        }
    p = settings.get(PLAYER_SECTION, {})
    rows[PLAYER_SECTION] = {
        "shuffle": p.get("shuffle", False),
        "skip_button": p.get("skip_button", None),  # None -> firmware default GPIO2, no line written
        "preview": p.get("preview", False),
        "preview_seconds": p.get("preview_seconds", None),  # None -> firmware default 30, no line written
        "recursive": p.get("recursive", False),
        "root_dir": p.get("root_dir", ""),  # "" -> SD card root, no line written
    }
    return rows


def default_rows():
    rows = {chip: {"enabled": True, "cs": DEFAULT_CS[chip], "gap": None, "volume": None}
            for chip in CHIP_ORDER}
    rows[PLAYER_SECTION] = {"shuffle": False, "skip_button": None, "preview": False,
                             "preview_seconds": None, "recursive": False, "root_dir": ""}
    return rows


def generate_ini(rows):
    out = [INI_HEADER]
    out.append("[player]")
    out.append(f"shuffle = {'yes' if rows[PLAYER_SECTION]['shuffle'] else 'no'}")
    if rows[PLAYER_SECTION]["skip_button"] is not None:
        out.append(f"skip_button = {int(rows[PLAYER_SECTION]['skip_button'])}")
    out.append(f"preview = {'yes' if rows[PLAYER_SECTION]['preview'] else 'no'}")
    if rows[PLAYER_SECTION]["preview_seconds"] is not None:
        out.append(f"preview_seconds = {int(rows[PLAYER_SECTION]['preview_seconds'])}")
    out.append(f"recursive = {'yes' if rows[PLAYER_SECTION]['recursive'] else 'no'}")
    if rows[PLAYER_SECTION]["root_dir"]:
        out.append(f"root_dir = {rows[PLAYER_SECTION]['root_dir']}")
    out.append("")
    for chip in CHIP_ORDER:
        r = rows[chip]
        out.append(f"[{chip}]")
        out.append(f"enabled = {'yes' if r['enabled'] else 'no'}")
        out.append(f"cs      = {int(r['cs'])}")
        if r["gap"] is not None:
            out.append(f"gap     = {int(r['gap'])}")
        if r["volume"] is not None:
            out.append(f"volume  = {int(r['volume'])}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def validate(rows):
    """Return (errors, warnings) -- both lists of strings."""
    errors, warnings = [], []
    used = {}

    skip_gpio = rows[PLAYER_SECTION]["skip_button"]
    if skip_gpio is None:
        skip_gpio = DEFAULT_SKIP_BUTTON_GPIO
    else:
        try:
            skip_gpio = int(skip_gpio)
            if not (CS_MIN <= skip_gpio <= CS_MAX):
                errors.append(f"skip_button GPIO{skip_gpio} out of range ({CS_MIN}-{CS_MAX})")
        except (TypeError, ValueError):
            errors.append(f"skip_button '{rows[PLAYER_SECTION]['skip_button']}' is not a number")
            skip_gpio = None
    # Reserved dynamically (not in the static RESERVED_PINS table) since it's
    # configurable -- mirrors slave_bus.c's slave_bus_set_skip_button_gpio().
    reserved = dict(RESERVED_PINS)
    if skip_gpio is not None:
        reserved[skip_gpio] = "skip button"

    if rows[PLAYER_SECTION]["preview_seconds"] is not None:
        try:
            ps = int(rows[PLAYER_SECTION]["preview_seconds"])
            if ps <= 0:
                errors.append(f"preview_seconds {ps} must be > 0")
        except (TypeError, ValueError):
            errors.append(f"preview_seconds '{rows[PLAYER_SECTION]['preview_seconds']}' is not a number")

    # Mirrors player_config.c's own length guard (a longer value is rejected
    # there, not truncated) -- ROOT_DIR_BUF_SZ counts the terminating NUL too.
    if len(rows[PLAYER_SECTION]["root_dir"]) >= ROOT_DIR_BUF_SZ:
        errors.append(f"root_dir is too long (max {ROOT_DIR_BUF_SZ - 1} characters)")

    for chip in CHIP_ORDER:
        r = rows[chip]
        name = DISPLAY[chip]
        try:
            cs = int(r["cs"])
        except (TypeError, ValueError):
            errors.append(f"{name}: CS '{r['cs']}' is not a number")
            continue
        if not (CS_MIN <= cs <= CS_MAX):
            errors.append(f"{name}: CS GPIO{cs} out of range ({CS_MIN}-{CS_MAX})")
        if r["gap"] is not None:
            try:
                g = int(r["gap"])
                if g < 0:
                    errors.append(f"{name}: gap {g} is negative")
            except (TypeError, ValueError):
                errors.append(f"{name}: gap '{r['gap']}' is not a number")
        if r["volume"] is not None:
            try:
                vol = int(r["volume"])
                if not (0 <= vol <= 255):
                    errors.append(f"{name}: volume {vol} out of range (0-255)")
            except (TypeError, ValueError):
                errors.append(f"{name}: volume '{r['volume']}' is not a number")
        if not r["enabled"]:
            continue
        if cs in reserved:
            warnings.append(f"{name}: CS GPIO{cs} collides with {reserved[cs]}")
        if cs in used:
            warnings.append(f"{name}: CS GPIO{cs} also used by {used[cs]}")
        else:
            used[cs] = name
    return errors, warnings


def resolve_config_path(path):
    """If `path` is a directory, apply the firmware's rule (player_config.c
    player_config_autoload): prefer 'vgmplay.ini', else the
    alphabetically-first 'vgmplay*.ini' (case-insensitive) in it. Returns the
    resolved file path (may not exist), or `path` unchanged when it's a file.
    """
    if not os.path.isdir(path):
        return path
    exact = os.path.join(path, "vgmplay.ini")
    if os.path.isfile(exact):
        return exact
    hits = [p for p in glob.glob(os.path.join(path, "*"))
            if os.path.isfile(p)
            and re.fullmatch(r"vgmplay.*\.ini", os.path.basename(p), re.IGNORECASE)]
    return sorted(hits, key=lambda p: os.path.basename(p).lower())[0] if hits else exact


# --------------------------------------------------------------------------
# CLI (headless) mode
# --------------------------------------------------------------------------

def run_check(path):
    path = resolve_config_path(path)
    with open(path, "r", encoding="utf-8-sig") as f:
        text = f.read()
    settings, notes = parse_ini(text)
    rows = rows_from_settings(settings)
    print(f"# parsed {path}\n")
    p = rows[PLAYER_SECTION]
    skip_disp = "default(2)" if p["skip_button"] is None else p["skip_button"]
    prevsec_disp = "default(30)" if p["preview_seconds"] is None else p["preview_seconds"]
    root_disp = "(SD card root)" if not p["root_dir"] else p["root_dir"]
    print(f"  [player]   shuffle={p['shuffle']} skip_button={skip_disp} "
          f"preview={p['preview']} preview_seconds={prevsec_disp} recursive={p['recursive']} "
          f"root_dir={root_disp}")
    for chip in CHIP_ORDER:
        r = rows[chip]
        gap = "default" if r["gap"] is None else r["gap"]
        vol = "default(100)" if r["volume"] is None else r["volume"]
        print(f"  {DISPLAY[chip]:<10} enabled={str(r['enabled']):<5} cs=GPIO{r['cs']:<2} gap={gap} volume={vol}")
    errors, warnings = validate(rows)
    for n in notes:
        print(f"\nnote: {n}")
    for w in warnings:
        print(f"warning: {w}")
    for e in errors:
        print(f"ERROR: {e}")
    return 1 if errors else 0


# --------------------------------------------------------------------------
# GUI
# --------------------------------------------------------------------------

def run_gui(initial_path=None):
    import tkinter as tk
    from tkinter import ttk, filedialog, messagebox

    if initial_path:
        initial_path = resolve_config_path(initial_path)

    root = tk.Tk()
    root.title("vgmplay.ini editor")
    root.minsize(640, 460)

    # sd_root_hint is the folder the Start-folder Browse... dialog treats as
    # the SD card root, so it can turn an absolute pick into the
    # card-relative path root_dir needs. It tracks wherever vgmplay.ini
    # itself lives -- known once a file has been opened or saved, or (even
    # before that) if the tool was pointed at the SD card / its ini path on
    # the command line.
    state = {"path": None,
             "sd_root_hint": os.path.dirname(os.path.abspath(initial_path)) if initial_path else None}
    vars_ = {}  # chip -> {"enabled": BooleanVar, "cs": StringVar, "gap": StringVar, "volume": StringVar}
    shuffle_var = tk.BooleanVar(value=False)     # [player] shuffle
    skip_button_var = tk.StringVar(value="")     # [player] skip_button (blank = default 2)
    preview_var = tk.BooleanVar(value=False)     # [player] preview
    preview_seconds_var = tk.StringVar(value="") # [player] preview_seconds (blank = default 30)
    recursive_var = tk.BooleanVar(value=False)   # [player] recursive
    root_dir_var = tk.StringVar(value="")        # [player] root_dir (blank = SD card root)

    # ---- widgets ----
    pathvar = tk.StringVar(value="(new file - not saved yet)")
    ttk.Label(root, textvariable=pathvar, anchor="w",
              relief="groove", padding=(6, 3)).pack(fill="x", padx=8, pady=(8, 4))

    playerf = ttk.Frame(root, padding=(8, 0))
    playerf.pack(fill="x")
    row1 = ttk.Frame(playerf)
    row1.pack(fill="x")
    ttk.Checkbutton(row1, text="Shuffle playback (random order, re-shuffled every pass)",
                    variable=shuffle_var).pack(side="left")
    ttk.Label(row1, text="Skip button GPIO:").pack(side="left", padx=(18, 4))
    ttk.Spinbox(row1, from_=CS_MIN, to=CS_MAX, width=5, textvariable=skip_button_var).pack(side="left")
    ttk.Label(row1, text="(blank = default 2)", foreground="#777").pack(side="left", padx=(4, 0))

    row2 = ttk.Frame(playerf)
    row2.pack(fill="x", pady=(4, 0))
    ttk.Checkbutton(row2, text="Preview mode (cut every song short)",
                    variable=preview_var).pack(side="left")
    ttk.Label(row2, text="Preview seconds:").pack(side="left", padx=(18, 4))
    ttk.Spinbox(row2, from_=1, to=9999, width=6, textvariable=preview_seconds_var).pack(side="left")
    ttk.Label(row2, text="(blank = default 30)", foreground="#777").pack(side="left", padx=(4, 0))

    row3 = ttk.Frame(playerf)
    row3.pack(fill="x", pady=(4, 0))
    ttk.Checkbutton(row3, text="Recursive (walk every subfolder, not just the start folder)",
                    variable=recursive_var).pack(side="left")

    row4 = ttk.Frame(playerf)
    row4.pack(fill="x", pady=(4, 0))
    ttk.Label(row4, text="Start folder (SD-relative):").pack(side="left")
    ttk.Entry(row4, width=30, textvariable=root_dir_var).pack(side="left", padx=(4, 4))
    ttk.Button(row4, text="Browse...", command=lambda: do_browse_root_dir()).pack(side="left")

    row4b = ttk.Frame(playerf)
    row4b.pack(fill="x")
    ttk.Label(row4b, text="(blank = SD card root; combine with Recursive to walk just this "
                          "folder; Browse needs the SD card's vgmplay.ini opened or saved first)",
              foreground="#777").pack(side="left")

    grid = ttk.Frame(root, padding=8)
    grid.pack(fill="x")
    for col, txt in enumerate(("Chip", "Enabled", "CS GPIO", "Gap (us)", "Volume (%)", "")):
        ttk.Label(grid, text=txt, font=("TkDefaultFont", 9, "bold")).grid(
            row=0, column=col, padx=6, pady=(0, 6), sticky="w")

    for i, chip in enumerate(CHIP_ORDER, start=1):
        en = tk.BooleanVar(value=True)
        cs = tk.StringVar(value=str(DEFAULT_CS[chip]))
        gap = tk.StringVar(value="")
        volume = tk.StringVar(value="")
        vars_[chip] = {"enabled": en, "cs": cs, "gap": gap, "volume": volume}

        ttk.Label(grid, text=DISPLAY[chip]).grid(row=i, column=0, padx=6, pady=2, sticky="w")
        ttk.Checkbutton(grid, variable=en).grid(row=i, column=1, padx=6, pady=2)
        ttk.Spinbox(grid, from_=CS_MIN, to=CS_MAX, width=5, textvariable=cs).grid(
            row=i, column=2, padx=6, pady=2)
        ttk.Entry(grid, width=7, textvariable=gap).grid(row=i, column=3, padx=6, pady=2)
        ttk.Spinbox(grid, from_=0, to=255, width=5, textvariable=volume).grid(
            row=i, column=4, padx=6, pady=2)
        dg = DEFAULT_GAP[chip]
        # `dg` can legitimately be 0 (YM2151's burst default) -- must check
        # "is not None", not truthiness, or 0 falls through to the wrong
        # "default gap 40" branch below.
        hint = f"default gap {dg}" if dg is not None else "default gap 40"
        ttk.Label(grid, text=f"(blank = {hint}; volume blank = 100)", foreground="#777").grid(
            row=i, column=5, padx=6, pady=2, sticky="w")

    btns = ttk.Frame(root, padding=(8, 4))
    btns.pack(fill="x")

    log = tk.Text(root, height=9, wrap="word", state="disabled",
                  background="#f4f4f4", relief="flat")
    log.pack(fill="both", expand=True, padx=8, pady=(4, 8))

    def say(*lines):
        log.configure(state="normal")
        log.delete("1.0", "end")
        log.insert("end", "\n".join(lines))
        log.configure(state="disabled")

    # ---- form <-> rows ----
    def rows_from_form():
        rows = {}
        for chip in CHIP_ORDER:
            v = vars_[chip]
            g = v["gap"].get().strip()
            vol = v["volume"].get().strip()
            rows[chip] = {
                "enabled": bool(v["enabled"].get()),
                "cs": v["cs"].get().strip(),
                "gap": (int(g) if re.fullmatch(r"\d+", g) else (None if g == "" else g)),
                "volume": (int(vol) if re.fullmatch(r"\d+", vol) else (None if vol == "" else vol)),
            }
        skip = skip_button_var.get().strip()
        prevsec = preview_seconds_var.get().strip()
        rows[PLAYER_SECTION] = {
            "shuffle": bool(shuffle_var.get()),
            "skip_button": (int(skip) if re.fullmatch(r"\d+", skip) else (None if skip == "" else skip)),
            "preview": bool(preview_var.get()),
            "preview_seconds": (int(prevsec) if re.fullmatch(r"\d+", prevsec) else (None if prevsec == "" else prevsec)),
            "recursive": bool(recursive_var.get()),
            "root_dir": normalize_root_dir(root_dir_var.get().strip()),
        }
        return rows

    def form_from_rows(rows):
        for chip in CHIP_ORDER:
            v = vars_[chip]
            r = rows[chip]
            v["enabled"].set(bool(r["enabled"]))
            v["cs"].set(str(r["cs"]))
            v["gap"].set("" if r["gap"] is None else str(r["gap"]))
            v["volume"].set("" if r["volume"] is None else str(r["volume"]))
        p = rows[PLAYER_SECTION]
        shuffle_var.set(bool(p["shuffle"]))
        skip_button_var.set("" if p["skip_button"] is None else str(p["skip_button"]))
        preview_var.set(bool(p["preview"]))
        preview_seconds_var.set("" if p["preview_seconds"] is None else str(p["preview_seconds"]))
        recursive_var.set(bool(p["recursive"]))
        root_dir_var.set(p["root_dir"])

    def do_validate(show_ok=True):
        rows = rows_from_form()
        errors, warnings = validate(rows)
        msg = []
        if errors:
            msg.append("ERRORS (fix before flashing):")
            msg += [f"  - {e}" for e in errors]
        if warnings:
            if msg:
                msg.append("")
            msg.append("Warnings (allowed, just double-check your wiring):")
            msg += [f"  - {w}" for w in warnings]
        if not msg and show_ok:
            msg = ["Looks good - no problems found."]
        say(*msg)
        return errors, warnings

    def do_open(path=None):
        if path is None:
            path = filedialog.askopenfilename(
                title="Open vgmplay.ini",
                filetypes=[("INI files", "*.ini"), ("All files", "*.*")])
        if not path:
            return
        try:
            with open(path, "r", encoding="utf-8-sig") as f:
                text = f.read()
        except OSError as e:
            messagebox.showerror("Open failed", str(e))
            return
        settings, notes = parse_ini(text)
        form_from_rows(rows_from_settings(settings))
        state["path"] = path
        state["sd_root_hint"] = os.path.dirname(os.path.abspath(path))
        pathvar.set(path)
        head = [f"Loaded {os.path.basename(path)}."]
        if notes:
            head.append("")
            head.append("Notes about the file:")
            head += [f"  - {n}" for n in notes]
        say(*head)
        do_validate(show_ok=not notes)

    def _write(path):
        errors, _ = do_validate(show_ok=False)
        if errors and not messagebox.askyesno(
                "Save anyway?",
                "There are errors (see the list at the bottom).\nSave the file anyway?"):
            return False
        try:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(generate_ini(rows_from_form()))
        except OSError as e:
            messagebox.showerror("Save failed", str(e))
            return False
        state["path"] = path
        state["sd_root_hint"] = os.path.dirname(os.path.abspath(path))
        pathvar.set(path)
        cur = log.get("1.0", "end").strip()
        say(f"Saved {path}", *(("", cur) if cur else ()))
        return True

    def do_save():
        if state["path"]:
            _write(state["path"])
        else:
            do_save_as()

    def do_save_as():
        path = filedialog.asksaveasfilename(
            title="Save vgmplay.ini", defaultextension=".ini",
            initialfile="vgmplay.ini",
            filetypes=[("INI files", "*.ini"), ("All files", "*.*")])
        if path:
            _write(path)

    def do_reset():
        if messagebox.askyesno("Reset", "Reset every chip to the firmware defaults?"):
            form_from_rows(default_rows())
            say("Reset to firmware defaults (not saved yet).")

    def do_browse_root_dir():
        sd_root = state["sd_root_hint"]
        if not sd_root:
            messagebox.showinfo(
                "SD card root unknown",
                "Open this vgmplay.ini from the SD card (or Save/Save As onto "
                "it) first, so Browse knows where the SD card root is.")
            return
        chosen = filedialog.askdirectory(
            title="Select start folder (must be inside the SD card)",
            initialdir=sd_root, mustexist=True)
        if not chosen:
            return
        rel = os.path.relpath(os.path.abspath(chosen), sd_root)
        if rel == os.curdir:
            root_dir_var.set("")
            return
        if rel.split(os.sep)[0] == os.pardir:
            messagebox.showerror(
                "Outside the SD card",
                f'"{chosen}" is not inside the SD card root\n({sd_root}).\n'
                "Pick a folder under the SD card instead.")
            return
        root_dir_var.set(normalize_root_dir(rel.replace(os.sep, "/")))

    ttk.Button(btns, text="Validate", command=lambda: do_validate()).pack(side="left")
    ttk.Button(btns, text="Reset to defaults", command=do_reset).pack(side="left", padx=(6, 0))
    ttk.Button(btns, text="Save", command=do_save).pack(side="right")
    ttk.Button(btns, text="Save As...", command=do_save_as).pack(side="right", padx=(0, 6))
    ttk.Button(btns, text="Open...", command=lambda: do_open()).pack(side="right", padx=(0, 6))

    menubar = tk.Menu(root)
    filem = tk.Menu(menubar, tearoff=0)
    filem.add_command(label="Open...", accelerator="Ctrl+O", command=lambda: do_open())
    filem.add_command(label="Save", accelerator="Ctrl+S", command=do_save)
    filem.add_command(label="Save As...", command=do_save_as)
    filem.add_separator()
    filem.add_command(label="Quit", command=root.destroy)
    menubar.add_cascade(label="File", menu=filem)
    helpm = tk.Menu(menubar, tearoff=0)
    helpm.add_command(label="About", command=lambda: messagebox.showinfo(
        "About",
        "vgmplay.ini editor\n\nEdits the SD-card config for the VGM multi-MCU "
        "player.\nReserved master GPIOs: 0/1 (OLED), the skip button's GPIO "
        "(default 2, configurable), 10/11 (slave bus), 16-19 (SD).\n"
        "CS GPIO range: 0-28."))
    menubar.add_cascade(label="Help", menu=helpm)
    root.config(menu=menubar)
    root.bind("<Control-o>", lambda e: do_open())
    root.bind("<Control-s>", lambda e: do_save())

    if initial_path and os.path.isfile(initial_path):
        do_open(initial_path)
    else:
        form_from_rows(default_rows())
        say("Showing firmware defaults. Open your SD card's vgmplay.ini, or "
            "edit here and Save As to the card.")

    root.mainloop()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("path", nargs="?",
                    help="vgmplay.ini to open, or a directory (e.g. the SD card) "
                         "to pick vgmplay.ini / the first vgmplay*.ini from")
    ap.add_argument("--check", metavar="PATH",
                    help="parse PATH (file or directory), print the result, exit (no GUI)")
    args = ap.parse_args(argv)
    if args.check:
        return run_check(args.check)
    run_gui(args.path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
