#!/usr/bin/env python3
"""GUI editor for the VGM multi-MCU player's SD-card config file (vgmplay.ini).

Per sound chip: enable/disable, chip-select GPIO, and an optional per-byte
CS-pulse gap (microseconds). Mirrors the firmware parser in
master/src/player_config.c -- section names ignore case / '-' / '_' / space,
the same key aliases are accepted, and the same reserved-pin / duplicate-CS
checks are surfaced as warnings.

Standard library only (tkinter). Run with no arguments for the GUI, or
`--check FILE` to parse a file and print the result on the console.
"""

import argparse
import glob
import os
import re
import sys

# (canonical section, display name, default CS GPIO, default gap us or None)
# Order = the order sections are written back out (matches firmware/vgmplay.ini).
CHIPS = [
    ("sn76489", "SN76489",   12, None),
    ("ym2612",  "YM2612",    13, None),
    ("ay8910",  "AY-3-8910", 14, 80),
    ("ym2413",  "YM2413",    15, None),
    ("ym2151",  "YM2151",    20, 120),
    ("ym2203",  "YM2203",    21, None),
    ("scc",     "SCC",       22, None),
    ("segapcm", "SegaPCM",   26, None),
]
CHIP_ORDER = [c[0] for c in CHIPS]
DISPLAY = {c[0]: c[1] for c in CHIPS}
DEFAULT_CS = {c[0]: c[2] for c in CHIPS}
DEFAULT_GAP = {c[0]: c[3] for c in CHIPS}

# normalized section name -> canonical
SECTION_ALIASES = {
    "sn76489": "sn76489",
    "ym2413": "ym2413",
    "ym2612": "ym2612",
    "ay8910": "ay8910", "ay38910": "ay8910",
    "ym2151": "ym2151",
    "ym2203": "ym2203",
    "scc": "scc", "k051649": "scc",
    "segapcm": "segapcm",
}

# normalized key (lower, '-'/'_'/space removed) -> field
KEY_ALIASES = {
    "enabled": "enabled", "enable": "enabled", "present": "enabled", "on": "enabled",
    "cs": "cs", "csgpio": "cs", "cspin": "cs", "pin": "cs",
    "gap": "gap", "gapus": "gap",
}

BOOL_TRUE = {"1", "on", "yes", "true", "enabled", "enable"}
BOOL_FALSE = {"0", "off", "no", "false", "disabled", "disable"}

# GPIO -> what the master already uses it for (a CS here fights that peripheral)
RESERVED_PINS = {
    0: "OLED I2C0 SDA", 1: "OLED I2C0 SCL", 2: "skip button",
    10: "slave bus SPI1 SCK", 11: "slave bus SPI1 MOSI",
    16: "SD card SPI0 MISO", 17: "SD card SPI0 CS",
    18: "SD card SPI0 SCK", 19: "SD card SPI0 MOSI",
}
CS_MIN, CS_MAX = 0, 28

INI_HEADER = """\
; vgmplay.ini -- VGM multi-MCU player (master) configuration
; Generated by tools/config_gui/vgmplay_config_gui.py -- hand edits to
; comments are not preserved when this tool rewrites the file.
;
; Copy to the ROOT of the SD card (next to the .vgm/.vgz files). Optional:
; with no file the firmware's built-in defaults are used. Section names
; ignore case, '-', '_' and spaces. Lines starting with ; or # are comments.
"""


def _norm(s):
    return re.sub(r"[-_ ]", "", s.strip().lower())


def parse_bool(v):
    lv = v.strip().lower()
    if lv in BOOL_TRUE:
        return True
    if lv in BOOL_FALSE:
        return False
    return None


def parse_ini(text):
    """Return (settings, notes).

    settings: {canonical_chip: {"enabled": bool?, "cs": int?, "gap": int?}}
    notes:    list of human-readable strings about anything odd in the file.
    """
    settings = {}
    notes = []
    cur = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line[0] in ";#":
            continue
        if line.startswith("["):
            end = line.find("]")
            if end < 0:
                notes.append(f"line {lineno}: malformed section header, ignored")
                continue
            name = line[1:end].strip()
            cur = SECTION_ALIASES.get(_norm(name))
            if cur is None:
                notes.append(f"line {lineno}: unknown chip section [{name}], skipped")
            continue
        if "=" not in line:
            notes.append(f"line {lineno}: no '=' , ignored ({line!r})")
            continue
        rawkey, rawval = line.split("=", 1)
        key = KEY_ALIASES.get(_norm(rawkey))
        val = re.split(r"[;#]", rawval, 1)[0].strip()
        if cur is None:
            notes.append(f"line {lineno}: '{rawkey.strip()}' outside any [chip] section, skipped")
            continue
        if key is None:
            notes.append(f"line {lineno}: unknown key '{rawkey.strip()}', ignored")
            continue
        d = settings.setdefault(cur, {})
        if key == "enabled":
            b = parse_bool(val)
            if b is None:
                notes.append(f"line {lineno}: bad boolean '{val}' for {DISPLAY[cur]}")
            else:
                d["enabled"] = b
        else:  # cs / gap
            if not re.fullmatch(r"\d+", val):
                notes.append(f"line {lineno}: bad number '{val}' for {key} ({DISPLAY[cur]})")
            else:
                d[key] = int(val)
    return settings, notes


def rows_from_settings(settings):
    """Merge parsed settings over the built-in defaults into a full row dict."""
    rows = {}
    for chip in CHIP_ORDER:
        s = settings.get(chip, {})
        rows[chip] = {
            "enabled": s.get("enabled", True),
            "cs": s.get("cs", DEFAULT_CS[chip]),
            "gap": s.get("gap", None),  # None -> use firmware default, no line written
        }
    return rows


def default_rows():
    return {chip: {"enabled": True, "cs": DEFAULT_CS[chip], "gap": None}
            for chip in CHIP_ORDER}


def generate_ini(rows):
    out = [INI_HEADER]
    for chip in CHIP_ORDER:
        r = rows[chip]
        out.append(f"[{chip}]")
        out.append(f"enabled = {'yes' if r['enabled'] else 'no'}")
        out.append(f"cs      = {int(r['cs'])}")
        if r["gap"] is not None:
            out.append(f"gap     = {int(r['gap'])}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def validate(rows):
    """Return (errors, warnings) -- both lists of strings."""
    errors, warnings = [], []
    used = {}
    for chip in CHIP_ORDER:
        r = rows[chip]
        name = DISPLAY[chip]
        try:
            cs = int(r["cs"])
        except (TypeError, ValueError):
            errors.append(f"{name}: CS '{r['cs']}' is not a number")
            continue
        if not (CS_MIN <= cs <= CS_MAX):
            errors.append(f"{name}: CS GPIO{cs} out of range ({CS_MIN}-{CS_MAX})")
        if r["gap"] is not None:
            try:
                g = int(r["gap"])
                if g < 0:
                    errors.append(f"{name}: gap {g} is negative")
            except (TypeError, ValueError):
                errors.append(f"{name}: gap '{r['gap']}' is not a number")
        if not r["enabled"]:
            continue
        if cs in RESERVED_PINS:
            warnings.append(f"{name}: CS GPIO{cs} collides with {RESERVED_PINS[cs]}")
        if cs in used:
            warnings.append(f"{name}: CS GPIO{cs} also used by {used[cs]}")
        else:
            used[cs] = name
    return errors, warnings


def resolve_config_path(path):
    """If `path` is a directory, apply the firmware's rule (player_config.c
    player_config_autoload): prefer 'vgmplay.ini', else the
    alphabetically-first 'vgmplay*.ini' (case-insensitive) in it. Returns the
    resolved file path (may not exist), or `path` unchanged when it's a file.
    """
    if not os.path.isdir(path):
        return path
    exact = os.path.join(path, "vgmplay.ini")
    if os.path.isfile(exact):
        return exact
    hits = [p for p in glob.glob(os.path.join(path, "*"))
            if os.path.isfile(p)
            and re.fullmatch(r"vgmplay.*\.ini", os.path.basename(p), re.IGNORECASE)]
    return sorted(hits, key=lambda p: os.path.basename(p).lower())[0] if hits else exact


# --------------------------------------------------------------------------
# CLI (headless) mode
# --------------------------------------------------------------------------

def run_check(path):
    path = resolve_config_path(path)
    with open(path, "r", encoding="utf-8-sig") as f:
        text = f.read()
    settings, notes = parse_ini(text)
    rows = rows_from_settings(settings)
    print(f"# parsed {path}\n")
    for chip in CHIP_ORDER:
        r = rows[chip]
        gap = "default" if r["gap"] is None else r["gap"]
        print(f"  {DISPLAY[chip]:<10} enabled={str(r['enabled']):<5} cs=GPIO{r['cs']:<2} gap={gap}")
    errors, warnings = validate(rows)
    for n in notes:
        print(f"\nnote: {n}")
    for w in warnings:
        print(f"warning: {w}")
    for e in errors:
        print(f"ERROR: {e}")
    return 1 if errors else 0


# --------------------------------------------------------------------------
# GUI
# --------------------------------------------------------------------------

def run_gui(initial_path=None):
    import tkinter as tk
    from tkinter import ttk, filedialog, messagebox

    if initial_path:
        initial_path = resolve_config_path(initial_path)

    root = tk.Tk()
    root.title("vgmplay.ini editor")
    root.minsize(560, 460)

    state = {"path": None}
    vars_ = {}  # chip -> {"enabled": BooleanVar, "cs": StringVar, "gap": StringVar}

    # ---- widgets ----
    pathvar = tk.StringVar(value="(new file - not saved yet)")
    ttk.Label(root, textvariable=pathvar, anchor="w",
              relief="groove", padding=(6, 3)).pack(fill="x", padx=8, pady=(8, 4))

    grid = ttk.Frame(root, padding=8)
    grid.pack(fill="x")
    for col, txt in enumerate(("Chip", "Enabled", "CS GPIO", "Gap (us)", "")):
        ttk.Label(grid, text=txt, font=("TkDefaultFont", 9, "bold")).grid(
            row=0, column=col, padx=6, pady=(0, 6), sticky="w")

    for i, chip in enumerate(CHIP_ORDER, start=1):
        en = tk.BooleanVar(value=True)
        cs = tk.StringVar(value=str(DEFAULT_CS[chip]))
        gap = tk.StringVar(value="")
        vars_[chip] = {"enabled": en, "cs": cs, "gap": gap}

        ttk.Label(grid, text=DISPLAY[chip]).grid(row=i, column=0, padx=6, pady=2, sticky="w")
        ttk.Checkbutton(grid, variable=en).grid(row=i, column=1, padx=6, pady=2)
        ttk.Spinbox(grid, from_=CS_MIN, to=CS_MAX, width=5, textvariable=cs).grid(
            row=i, column=2, padx=6, pady=2)
        ttk.Entry(grid, width=7, textvariable=gap).grid(row=i, column=3, padx=6, pady=2)
        dg = DEFAULT_GAP[chip]
        hint = f"default gap {dg}" if dg else "default gap 40"
        ttk.Label(grid, text=f"(blank = {hint})", foreground="#777").grid(
            row=i, column=4, padx=6, pady=2, sticky="w")

    btns = ttk.Frame(root, padding=(8, 4))
    btns.pack(fill="x")

    log = tk.Text(root, height=9, wrap="word", state="disabled",
                  background="#f4f4f4", relief="flat")
    log.pack(fill="both", expand=True, padx=8, pady=(4, 8))

    def say(*lines):
        log.configure(state="normal")
        log.delete("1.0", "end")
        log.insert("end", "\n".join(lines))
        log.configure(state="disabled")

    # ---- form <-> rows ----
    def rows_from_form():
        rows = {}
        for chip in CHIP_ORDER:
            v = vars_[chip]
            g = v["gap"].get().strip()
            rows[chip] = {
                "enabled": bool(v["enabled"].get()),
                "cs": v["cs"].get().strip(),
                "gap": (int(g) if re.fullmatch(r"\d+", g) else (None if g == "" else g)),
            }
        return rows

    def form_from_rows(rows):
        for chip in CHIP_ORDER:
            v = vars_[chip]
            r = rows[chip]
            v["enabled"].set(bool(r["enabled"]))
            v["cs"].set(str(r["cs"]))
            v["gap"].set("" if r["gap"] is None else str(r["gap"]))

    def do_validate(show_ok=True):
        rows = rows_from_form()
        errors, warnings = validate(rows)
        msg = []
        if errors:
            msg.append("ERRORS (fix before flashing):")
            msg += [f"  - {e}" for e in errors]
        if warnings:
            if msg:
                msg.append("")
            msg.append("Warnings (allowed, just double-check your wiring):")
            msg += [f"  - {w}" for w in warnings]
        if not msg and show_ok:
            msg = ["Looks good - no problems found."]
        say(*msg)
        return errors, warnings

    def do_open(path=None):
        if path is None:
            path = filedialog.askopenfilename(
                title="Open vgmplay.ini",
                filetypes=[("INI files", "*.ini"), ("All files", "*.*")])
        if not path:
            return
        try:
            with open(path, "r", encoding="utf-8-sig") as f:
                text = f.read()
        except OSError as e:
            messagebox.showerror("Open failed", str(e))
            return
        settings, notes = parse_ini(text)
        form_from_rows(rows_from_settings(settings))
        state["path"] = path
        pathvar.set(path)
        head = [f"Loaded {os.path.basename(path)}."]
        if notes:
            head.append("")
            head.append("Notes about the file:")
            head += [f"  - {n}" for n in notes]
        say(*head)
        do_validate(show_ok=not notes)

    def _write(path):
        errors, _ = do_validate(show_ok=False)
        if errors and not messagebox.askyesno(
                "Save anyway?",
                "There are errors (see the list at the bottom).\nSave the file anyway?"):
            return False
        try:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(generate_ini(rows_from_form()))
        except OSError as e:
            messagebox.showerror("Save failed", str(e))
            return False
        state["path"] = path
        pathvar.set(path)
        cur = log.get("1.0", "end").strip()
        say(f"Saved {path}", *(("", cur) if cur else ()))
        return True

    def do_save():
        if state["path"]:
            _write(state["path"])
        else:
            do_save_as()

    def do_save_as():
        path = filedialog.asksaveasfilename(
            title="Save vgmplay.ini", defaultextension=".ini",
            initialfile="vgmplay.ini",
            filetypes=[("INI files", "*.ini"), ("All files", "*.*")])
        if path:
            _write(path)

    def do_reset():
        if messagebox.askyesno("Reset", "Reset every chip to the firmware defaults?"):
            form_from_rows(default_rows())
            say("Reset to firmware defaults (not saved yet).")

    ttk.Button(btns, text="Validate", command=lambda: do_validate()).pack(side="left")
    ttk.Button(btns, text="Reset to defaults", command=do_reset).pack(side="left", padx=(6, 0))
    ttk.Button(btns, text="Save", command=do_save).pack(side="right")
    ttk.Button(btns, text="Save As...", command=do_save_as).pack(side="right", padx=(0, 6))
    ttk.Button(btns, text="Open...", command=lambda: do_open()).pack(side="right", padx=(0, 6))

    menubar = tk.Menu(root)
    filem = tk.Menu(menubar, tearoff=0)
    filem.add_command(label="Open...", accelerator="Ctrl+O", command=lambda: do_open())
    filem.add_command(label="Save", accelerator="Ctrl+S", command=do_save)
    filem.add_command(label="Save As...", command=do_save_as)
    filem.add_separator()
    filem.add_command(label="Quit", command=root.destroy)
    menubar.add_cascade(label="File", menu=filem)
    helpm = tk.Menu(menubar, tearoff=0)
    helpm.add_command(label="About", command=lambda: messagebox.showinfo(
        "About",
        "vgmplay.ini editor\n\nEdits the SD-card config for the VGM multi-MCU "
        "player.\nReserved master GPIOs: 0/1 (OLED), 2 (skip button), "
        "10/11 (slave bus), 16-19 (SD).\nCS GPIO range: 0-28."))
    menubar.add_cascade(label="Help", menu=helpm)
    root.config(menu=menubar)
    root.bind("<Control-o>", lambda e: do_open())
    root.bind("<Control-s>", lambda e: do_save())

    if initial_path and os.path.isfile(initial_path):
        do_open(initial_path)
    else:
        form_from_rows(default_rows())
        say("Showing firmware defaults. Open your SD card's vgmplay.ini, or "
            "edit here and Save As to the card.")

    root.mainloop()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("path", nargs="?",
                    help="vgmplay.ini to open, or a directory (e.g. the SD card) "
                         "to pick vgmplay.ini / the first vgmplay*.ini from")
    ap.add_argument("--check", metavar="PATH",
                    help="parse PATH (file or directory), print the result, exit (no GUI)")
    args = ap.parse_args(argv)
    if args.check:
        return run_check(args.check)
    run_gui(args.path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
